package com.arentios.gene.domain;

import java.util.ArrayList;

import com.arentios.gene.sequence.NeedlemanWunsch;
import com.arentios.gene.sequence.SmithWaterman;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        GeneSequence firstSequence = new GeneSequence("MPAVYGARLTTFEDSEKESEFGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLMVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIAKRSGDVYIPRGVSVPALDKDTLWEFQPKKIGEGDLLTGGDLYATVFENSLMQHHVALPPDAMGKITYIAPPGQYSLKDTVLELEFQGVKKQFTMLQTWPVRTPRPVATKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLPDGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERTGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSGALESFYEKFDPDFISIRTKAREVLQREDDLNEIVQLVGKDALAETDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIVHFNALANQAVEKAAGMDGQKITYSLIKHRLGDLFYRLVSQKFEDPAEGEEALVAKFKKLNEDLTAGFRALEDETR");
        GeneSequence secondSequence = new GeneSequence("MPAFYGGKLTTFEDDEKESEYGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLTVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIARISGDVYIPRGVSVPALDKDCLWEFQPNKFVEGDTITGGDLYATVFENTLMNHLVALPPDAMGKITYIAPAGQYSLKDTVIELEFQGIKKSYTMLQSWPVRTPRPVASKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLPDGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERNGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSTALESFYEKFDPDFINIRTKAREVLQREDDLNEIVQLVGKDALAEGDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIIHFYNLANQAVERAAGMDGQKITYTLIKHRLGDLFYRLVSQKFEDPAEGEDTLVEKFKKLYDDLNAGFRALEDETR");
      //  firstSequence.randomize(100);
      //  secondSequence = new GeneSequence(firstSequence);
      //  secondSequence.mutate(10);
        ArrayList<SequenceAlignment> sequencedGenes = NeedlemanWunsch.sequence(firstSequence, secondSequence);
        for(SequenceAlignment genes : sequencedGenes){
        	System.out.println(genes);
        }
        sequencedGenes = SmithWaterman.sequence(firstSequence, secondSequence);
        for(SequenceAlignment genes : sequencedGenes){
        	System.out.println(genes);
        }
    }
}
