package com.arentios.gene.domain;

import java.util.ArrayList;

import com.arentios.gene.sequence.NeedlemanWunsch;
import com.arentios.gene.sequence.SmithWaterman;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
       // Sequence firstSequence = new Sequence("MPAVYGARLTTFEDSEKESEFGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLMVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIAKRSGDVY");//IPRGVSVPALDKDTLWEFQPKKIGEGDLLTGGDLYATVFENSLMQHHVALPPDAMGKITYIAPPGQYSLKDTVLELEFQGVKKQFTMLQTWPVRTPRPVATKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLP");//DGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERTGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSGALESFYEKFDPDFISIRTKAREVLQREDDLNEIVQLVGKDALAETDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIVHFNALANQAVEKAAGMDGQKITYSLIKHRLGDLFYRLVSQKFEDPAEGEEALVAKFKKLNEDLTAGFRALEDETR");
       // Sequence secondSequence = new Sequence("MPAFYGGKLTTFEDDEKESEYGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLTVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIARISGDVY");//IPRGVSVPALDKDCLWEFQPNKFVEGDTITGGDLYATVFENTLMNHLVALPPDAMGKITYIAPAGQYSLKDTVIELEFQGIKKSYTMLQSWPVRTPRPVASKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLP");//DGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERNGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSTALESFYEKFDPDFINIRTKAREVLQREDDLNEIVQLVGKDALAEGDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIIHFYNLANQAVERAAGMDGQKITYTLIKHRLGDLFYRLVSQKFEDPAEGEDTLVEKFKKLYDDLNAGFRALEDETR");
		Sequence firstSequence = new Sequence("MPAVYGARL");
		Sequence secondSequence = new Sequence("MPAFYGG");
		
      //  ArrayList<SequenceAlignment> sequencedGenes = NeedlemanWunsch.sequence(firstSequence, secondSequence);
//        for(SequenceAlignment genes : sequencedGenes){
//        	System.out.println(genes);
//        }
      //  firstSequence = new GeneSequence("CGTGAATTCAT");
      //  secondSequence = new GeneSequence("GACTTAC");

		ArrayList<SequenceAlignment> sequencedGenes = SmithWaterman.sequence(firstSequence, secondSequence);
        for(SequenceAlignment genes : sequencedGenes){
        	System.out.println(genes);
        }
    }
}
