package com.arentios.gene.domain;

import java.util.ArrayList;

import com.arentios.gene.sequence.NeedlemanWunsch;
import com.arentios.gene.sequence.SmithWaterman;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        GeneSequence firstSequence = new GeneSequence("MPAVYGARLTTFEDSEKESEFGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLMVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIAKRSGDVY");//IPRGVSVPALDKDTLWEFQPKKIGEGDLLTGGDLYATVFENSLMQHHVALPPDAMGKITYIAPPGQYSLKDTVLELEFQGVKKQFTMLQTWPVRTPRPVATKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLP");//DGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERTGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSGALESFYEKFDPDFISIRTKAREVLQREDDLNEIVQLVGKDALAETDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIVHFNALANQAVEKAAGMDGQKITYSLIKHRLGDLFYRLVSQKFEDPAEGEEALVAKFKKLNEDLTAGFRALEDETR");
        GeneSequence secondSequence = new GeneSequence("MPAFYGGKLTTFEDDEKESEYGYVRKVSGPVVVADGMAGAAMYELVRVGHDNLIGEIIRLEGDSATIQVYEETAGLTVNDPVLRTHKPLSVELGPGILGNIFDGIQRPLKTIARISGDVY");//IPRGVSVPALDKDCLWEFQPNKFVEGDTITGGDLYATVFENTLMNHLVALPPDAMGKITYIAPAGQYSLKDTVIELEFQGIKKSYTMLQSWPVRTPRPVASKLAADTPLLTGQRVLDALFPSVLGGTCAIPGAFGCGKTVISQALSKYSNSDAVVYVGCGERGNEMAEVLMDFPQLTMTLP");//DGREESVMKRTTLVANTSNMPVAAREASIYTGITIAEYFRDMGYNVSMMADSTSRWAEALREISGRLAEMPADSGYPAYLAARLASFYERAGKVKCLGGPERNGSVTIVGAVSPPGGDFSDPVTSATLSIVQVFWGLDKKLAQRKHFPSVNWLISYSKYSTALESFYEKFDPDFINIRTKAREVLQREDDLNEIVQLVGKDALAEGDKITLETAKLLREDYLAQNAFTPYDKFCPFYKSVWMMRNIIHFYNLANQAVERAAGMDGQKITYTLIKHRLGDLFYRLVSQKFEDPAEGEDTLVEKFKKLYDDLNAGFRALEDETR");
      //  firstSequence.randomize(20);
      //  secondSequence = new GeneSequence(firstSequence);
      //  secondSequence.mutate(10);
        ArrayList<SequenceAlignment> sequencedGenes = NeedlemanWunsch.sequence(firstSequence, secondSequence);
//        for(SequenceAlignment genes : sequencedGenes){
//        	System.out.println(genes);
//        }
      //  firstSequence = new GeneSequence("CGTGAATTCAT");
      //  secondSequence = new GeneSequence("GACTTAC");

        sequencedGenes = SmithWaterman.sequence(firstSequence, secondSequence);
        for(SequenceAlignment genes : sequencedGenes){
        	System.out.println(genes);
        }
    }
}
